// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace E_commerce_website.Models
{
    public partial class OrderDetail
    {
        [Key]
        public int DetailID { get; set; }
        public int DetailOrderID { get; set; }
        public int DetailProductID { get; set; }
        [Required]
        [StringLength(50)]
        
        public string DetailName { get; set; }
        public int Quanity { get; set; }
        public double Price { get; set; }

        [ForeignKey(nameof(DetailOrderID))]
        [InverseProperty(nameof(Order.OrderDetails))]
        public virtual Order DetailOrder { get; set; }
        [ForeignKey(nameof(DetailProductID))]
        [InverseProperty(nameof(Product.OrderDetails))]
        public virtual Product DetailProduct { get; set; }
    }
}