// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace E_commerce_website.Models
{
    public partial class Order
    {
        public Order()
        {
            OrderDetails = new HashSet<OrderDetail>();
        }

        [Key]
        public int OrderID { get; set; }
        public int UserID { get; set; }
        public int OrderAmount { get; set; }
        [Required]
        [StringLength(10)]
        public string ShippingAddress { get; set; }
        [Required]
        [StringLength(10)]
        public string OrderAddress { get; set; }
        [Column(TypeName = "date")]
        public DateTime OrderDate { get; set; }
        public bool? OrderStatus { get; set; }
        public int? orderTrakingNumber { get; set; }
        public byte OrderShiped { get; set; }
        [Required]
        [StringLength(10)]
        public string OrderCountry { get; set; }
        [Required]
        [StringLength(10)]
        public string OrderCity { get; set; }
        [Required]
        [StringLength(50)]
        public string CustomerPhone { get; set; }
        [StringLength(50)]
        public string OrderPhone { get; set; }
        [StringLength(50)]
        public string OrderEmail { get; set; }

        [ForeignKey(nameof(UserID))]
        [InverseProperty("Orders")]
        public virtual User User { get; set; }
        [InverseProperty(nameof(OrderDetail.DetailOrder))]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}