// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace E_commerce_website.Models
{
    public partial class OrderItemsOption
    {
        [Key]
        public int OrderID { get; set; }
        [Key]
        public int UserID { get; set; }
        [Key]
        public int ProductID { get; set; }
        [Key]
        public int OptionID { get; set; }
        public int Quantity { get; set; }

        [ForeignKey(nameof(OptionID))]
        [InverseProperty("OrderItemsOptions")]
        public virtual Option Option { get; set; }
        [ForeignKey(nameof(OrderID))]
        [InverseProperty("OrderItemsOptions")]
        public virtual Order Order { get; set; }
        [ForeignKey(nameof(ProductID))]
        [InverseProperty("OrderItemsOptions")]
        public virtual Product Product { get; set; }
        [ForeignKey(nameof(UserID))]
        [InverseProperty("OrderItemsOptions")]
        public virtual User User { get; set; }
    }
}