// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace E_commerce_website.Models
{
    [Index(nameof(OptionID), Name = "IX_ProductOptions_OptionID")]
    [Index(nameof(ProductID), Name = "IX_ProductOptions_ProductID")]
    public partial class ProductOption
    {
        [Key]
        public int id { get; set; }
        public int OptionID { get; set; }
        public int ProductID { get; set; }

        [ForeignKey(nameof(OptionID))]
        [InverseProperty("ProductOptions")]
        public virtual Option Option { get; set; }
        [ForeignKey(nameof(ProductID))]
        [InverseProperty("ProductOptions")]
        public virtual Product Product { get; set; }
    }
}