// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace E_commerce_website.Models
{
    public partial class Product
    {
        public Product()
        {
            OrderDetails = new HashSet<OrderDetail>();
            ProductOptions = new HashSet<ProductOption>();
        }

        [Key]
        public int ProductID { get; set; }
        [Required]
        [StringLength(50)]
        public string ProductName { get; set; }
        public double ProductPrice { get; set; }
        public double? ProductWeight { get; set; }
        [Required]
        [StringLength(250)]
        public string ProductShortDes { get; set; }
        [StringLength(3000)]
        public string ProductLongDes { get; set; }
        [Required]
        [StringLength(200)]
        public string ProductImage { get; set; }
        public int ProductCategoryID { get; set; }
        public byte[] ProductUpdateDate { get; set; }
        public int ProductStock { get; set; }
        public int? VendorID { get; set; }

        [ForeignKey(nameof(ProductCategoryID))]
        [InverseProperty("Products")]
        public virtual ProductCategory ProductCategory { get; set; }
        [ForeignKey(nameof(VendorID))]
        [InverseProperty("Products")]
        public virtual Vendor Vendor { get; set; }
        [InverseProperty(nameof(OrderDetail.DetailProduct))]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        [InverseProperty(nameof(ProductOption.Product))]
        public virtual ICollection<ProductOption> ProductOptions { get; set; }
    }
}