// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace E_commerce_website.Models
{
    public partial class User
    {
        public User()
        {
            Orders = new HashSet<Order>();
        }

        [Key]
        public int UserID { get; set; }
        [Required]
        [StringLength(10)]
        public string UserEmail { get; set; }
        [Required]
        [StringLength(50)]
        public string UserPassword { get; set; }
        [Required]
        [StringLength(50)]
        public string UserFirstName { get; set; }
        [Required]
        [StringLength(50)]
        public string UserLastName { get; set; }
        [Required]
        [StringLength(10)]
        public string UserCity { get; set; }
        public byte UserEmailVerfied { get; set; }
        [Required]
        public byte[] UserRegisterDate { get; set; }
        [Required]
        [StringLength(50)]
        public string UserVerficationCode { get; set; }
        public int UserIP { get; set; }
        [Required]
        [StringLength(50)]
        public string UserPhone { get; set; }
        [Required]
        [StringLength(50)]
        public string UserCountry { get; set; }
        [Required]
        [StringLength(100)]
        public string UserAddress { get; set; }
        [StringLength(100)]
        public string UserAddress2 { get; set; }

        [InverseProperty(nameof(Order.User))]
        public virtual ICollection<Order> Orders { get; set; }
    }
}