// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace E_commerce_website.Models
{
    public partial class User
    {
        public User()
        {
            CartItems = new HashSet<CartItem>();
            OrderItemsOptions = new HashSet<OrderItemsOption>();
            Orders = new HashSet<Order>();
            UserRegisterDate = DateTime.Now;
        }

        [Key]
        public int UserID { get; set; }
        [Required]
        [StringLength(100)]
        public string UserEmail { get; set; }
        [Required]
        [StringLength(50)]
        public string UserPassword { get; set; }
        [Required]
        [StringLength(200)]
        public string UserName { get; set; }
        [Required]
        [StringLength(100)]
        public string UserCity { get; set; }
        public byte UserEmailVerfied { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime UserRegisterDate { get; set; }
        [StringLength(50)]
        public string UserVerficationCode { get; set; }
        [Required]
        [StringLength(50)]
        public string UserPhone { get; set; }
        [Required]
        [StringLength(50)]
        public string UserCountry { get; set; }
        [Required]
        [StringLength(100)]
        public string UserAddress { get; set; }

        [InverseProperty(nameof(CartItem.User))]
        public virtual ICollection<CartItem> CartItems { get; set; }
        [InverseProperty(nameof(OrderItemsOption.User))]
        public virtual ICollection<OrderItemsOption> OrderItemsOptions { get; set; }
        [InverseProperty(nameof(Order.User))]
        public virtual ICollection<Order> Orders { get; set; }
    }
}