// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace E_commerce_website.Models
{
    [Table("Vendor")]
    public partial class Vendor
    {
        public Vendor()
        {
            Products = new HashSet<Product>();
        }

        [Key]
        public int VendorID { get; set; }
        [Required]
        [StringLength(50)]
        public string VendorName { get; set; }
        [Required]
        [StringLength(50)]
        public string Address { get; set; }
        public int Phone { get; set; }
        [Required]
        [StringLength(50)]
        public string City { get; set; }
        [Required]
        [StringLength(10)]
        public string Email { get; set; }

        [InverseProperty(nameof(Product.Vendor))]
        public virtual ICollection<Product> Products { get; set; }
    }
}